# permissions for end users to edit gstconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gstconfig-editor-role
rules:
- apiGroups:
  - clusterops.simp.nl
  resources:
  - gstconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterops.simp.nl
  resources:
  - gstconfigs/status
  verbs:
  - get
