
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clusterops.simp.nl
  resources:
  - gstconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterops.simp.nl
  resources:
  - gstconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - clusterops.simp.nl
  resources:
  - gstconfigs/status
  verbs:
  - get
  - patch
  - update
